export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
export const SET_IS_REGISTER = 'SET_IS_REGISTER';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';
export const EDIT_USER_INFO_FAILURE = 'EDIT_USER_INFO_FAILURE';
export const EDIT_USER_INFO_SUCCESS = 'EDIT_USER_INFO_SUCCESS';
export const DELETE_USER_INFO_FAILURE = 'DELETE_USER_INFO_FAILURE';
export const DELETE_USER_INFO_SUCCESS = 'DELETE_USER_INFO_SUCCESS';
export const GET_USER_INFO_BY_ID_SUCCESS = 'GET_USER_INFO_BY_ID_SUCCESS';
export const GET_USER_INFO_BY_ID_FAILURE = 'GET_USER_INFO_BY_ID_FAILURE';

export const GET_USER_ACHIEVEMENTS_SUCCESS = 'GET_USER_ACHIEVEMENTS_SUCCESS';
export const GET_USER_ACHIEVEMENTS_FAILURE = 'GET_USER_ACHIEVEMENTS_FAILURE';

export const SUBSCRIBE_FOR_USER_SUCCESS = 'SUBSCRIBE_FOR_USER_SUCCESS';
export const SUBSCRIBE_FOR_USER_FAILURE = 'SUBSCRIBE_FOR_USER_FAILURE';

export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS__FAILURE = 'SEARCH_USERS__FAILURE';

export const GET_GOALS_SUCCESS = 'GET_GOALS_SUCCESS';
export const GET_GOALS_FAILURE = 'GET_GOALS_FAILURE';
export const EDIT_GOAL_FAILURE = 'EDIT_GOAL_FAILURE';
export const EDIT_GOAL_SUCCESS = 'EDIT_GOAL_SUCCESS';
export const UPDATE_GOAL_FAILURE = 'UPDATE_GOAL_FAILURE';
export const UPDATE_GOAL_SUCCESS = 'UPDATE_GOAL_SUCCESS';
export const GET_DEFAULT_GOALS_SUCCESS = 'GET_DEFAULT_GOALS_SUCCESS';
export const GET_DEFAULT_GOALS_FAILURE = 'GET_DEFAULT_GOALS_FAILURE';
export const GET_SEASON_GOALS_SUCCESS = 'GET_SEASON_GOALS_SUCCESS';
export const GET_SEASON_GOALS_FAILURE = 'GET_SEASON_GOALS_FAILURE';
export const GET_GOAL_BY_ID_SUCCESS = 'GET_GOAL_BY_ID_SUCCESS';
export const GET_GOAL_BY_ID_FAILURE = 'GET_GOAL_BY_ID_FAILURE';
export const POST_GOALS_SUCCESS = 'POST_GOALS_SUCCESS';
export const POST_GOALS_FAILURE = 'POST_GOALS_FAILURE';